apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-var-lib
  namespace: grafanamon
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi