apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsgrafana
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /mnt/data/nfspv01/grafana
    server: 10.0.0.100 
  persistentVolumeReclaimPolicy: Retain