apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-prometheus-server
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.100 
    path: /mnt/data/Gitlab/gitlab-prometheus-server 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-minio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.100 
    path: /mnt/data/Gitlab/gitlab-minio