apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloudssd
spec:
  storageClassName: nfs
  capacity:
    storage: 40Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /mnt/data/nextcloud
    server: 10.0.0.100 
  persistentVolumeReclaimPolicy: Retain