apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nextcloud
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30