apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ing-nextcloud
  namespace: nextcloud
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - nextcloud.dflocal.pt
    secretName: nextcloudtls
  rules:
  - host: nextcloud.dflocal.pt
    http:
      paths:
      - backend:
          serviceName: nextcloud
          servicePort: 80