apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - nextcloud.dflocal.com
    secretName: nextcloudtls
  rules:
  - host: nextcloud.dflocal.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80