kind: Service
apiVersion: v1
metadata:
  name: "nginx"
  namespace: df
spec:
  selector:
    app: "nginx"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 31115
  type: LoadBalancer