apiVersion: certmanager.k8s.io/v1beta1
kind: Certificate
metadata:
  name: tls-secret
  namespace: nextcloud
spec:
  secretName: nextcloudtls
  dnsNames:
  - nextcloud.dflocal.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - nextcloud.dflocal.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer