# This is a basic workflow that is manually triggered

name: Manual workflow


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
#  push:
#    branches: master
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'testenv'
        # Default value if no value is explicitly provided
        default: 'test'
        # Input has to be provided for the workflow to run
        required: true



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  clonningrep:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: clone rep
      #run: git clone https://github.com/Clichas/k8s.git
      run: echo $(ls -l)


  nginxdeploy:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: create namespace
      run: kubectl create ns nginxviagit || true
    # This step checks out a copy of your repository.
    - uses: Clichas/k8s@v1
    # This step references the directory that contains the action.
    - uses: ./.github/actions/nginx  
    # Runs a single command using the runners shell
    - name: run nginx deploy
      run: kubectl apply -f action.yaml -n nginxviagit
    
   
