# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Job Name'
        # Default value if no value is explicitly provided
        default: 'teste'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: Clichas/k8s
    - name: create namespace
      run: kubectl create ns nginxviagit || true
    # Runs a single command using the runners shell
    - name: run nginx deploy
      run: kubectl apply -f ./run/nginx.yaml -n nginxviagit
